//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/InputJoueur.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputJoueur : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputJoueur()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputJoueur"",
    ""maps"": [
        {
            ""name"": ""TirLucioles"",
            ""id"": ""e1382296-a909-4f6c-9f0b-5d3b33868d00"",
            ""actions"": [
                {
                    ""name"": ""Position Souris"",
                    ""type"": ""Value"",
                    ""id"": ""29c1b2fd-480f-4583-b489-5e2d3c71ab8e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Tir"",
                    ""type"": ""Button"",
                    ""id"": ""165ca871-36c6-4e5a-ba29-ade70b3fb8b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Annuler Tir"",
                    ""type"": ""Button"",
                    ""id"": ""4f5f0462-3fb4-47c2-b02b-ecb4d1166a0d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangerClavier"",
                    ""type"": ""Button"",
                    ""id"": ""f824336d-c6af-4e46-a16d-ba8ee54d3a58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ChangerManette"",
                    ""type"": ""Button"",
                    ""id"": ""59273020-8d23-417f-8b9a-bd2a9746cb10"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Position Manette"",
                    ""type"": ""Value"",
                    ""id"": ""8ab15790-7411-4e0d-8d89-3428995fa581"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f9da9772-4f73-40cf-a354-3b3dc063680f"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position Souris"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c9cfe16-e1e6-4d7b-800c-be455923cb74"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Manette"",
                    ""action"": ""Tir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f46c6d7-b0f6-44a2-a21c-cba95f87dc6d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f944f14e-760d-4604-9bb1-4ef979d323ad"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Clavier;Keyboard"",
                    ""action"": ""Annuler Tir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d63fea5e-c923-463b-b86d-586e04945706"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Manette;Gamepad"",
                    ""action"": ""Annuler Tir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd1b8092-fe78-4dbc-b4c3-f119243622d5"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangerClavier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ef9a41c-2172-4d00-9313-71da4d36a927"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangerManette"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5b3f7aa-7479-47ce-bf61-0fab2ad5fbe6"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position Manette"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Mort"",
            ""id"": ""546d5850-0886-486a-baa9-7debb20829f9"",
            ""actions"": [
                {
                    ""name"": ""LoadScene"",
                    ""type"": ""Button"",
                    ""id"": ""7fbc424d-1ecc-430c-a65b-c87833fa4e6f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""152fe9cc-202f-4968-bad7-e0aa3cabe010"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Dialogues"",
            ""id"": ""5c5bb117-c970-4a3e-8042-6977f5502c8b"",
            ""actions"": [
                {
                    ""name"": ""LireTexte"",
                    ""type"": ""Button"",
                    ""id"": ""784ddcd6-b2c3-453e-836a-ea00e16b92f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkipperTexte"",
                    ""type"": ""Button"",
                    ""id"": ""f50e2f34-db24-4e56-a513-9413270d4cc8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""890f56cd-8d06-424f-bcb9-b56ad4777e22"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LireTexte"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""512b97b8-4635-4fa0-9b78-de55d60db1db"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipperTexte"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player"",
            ""id"": ""29192838-daa3-4fb7-9d7f-5f9ee2ca1685"",
            ""actions"": [
                {
                    ""name"": ""Saut"",
                    ""type"": ""Button"",
                    ""id"": ""a93f6f19-5f42-4576-8907-c479334a803f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangerManette"",
                    ""type"": ""Button"",
                    ""id"": ""6a159ab3-d7cb-4ab5-8a75-8bdfa296892d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangerClavier"",
                    ""type"": ""Button"",
                    ""id"": ""120a735b-b904-4ec2-bfff-e06ae9316316"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Mouvement"",
                    ""type"": ""Value"",
                    ""id"": ""6003782c-b8c9-482a-bbfc-bf0cffc0b091"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Courrir"",
                    ""type"": ""Button"",
                    ""id"": ""c4fe28c2-f638-44c3-b011-1b0e34c54549"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Accroupir"",
                    ""type"": ""Button"",
                    ""id"": ""235ef93c-4304-470b-8cf4-7983ce2d7279"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attaque Physique"",
                    ""type"": ""Button"",
                    ""id"": ""13a79382-c2dc-46d5-b47c-cf73a6f3a1c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""f632c3a4-0877-4b0b-8925-d2b1836056d1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Enclencher Tir"",
                    ""type"": ""Button"",
                    ""id"": ""a49a9d94-930b-4743-ad87-a82ff828f806"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d59b10a9-82d7-491e-bf0c-48200980c495"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Saut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe6b1847-4098-4de5-bb3c-d88d0f2d9045"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Saut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard and Mouse"",
                    ""id"": ""bd7feb80-526a-41b3-886f-6b5321a6734b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouvement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4fc7c06a-7be2-4ae6-a165-4a6d3ce26044"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Mouvement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""63e04ec2-7453-4778-9e12-d1d27fcbdef5"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Mouvement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bf814507-80aa-4c92-8e83-9b0688beda08"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Mouvement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a10ea9e5-0394-4bd0-afbe-9ba86b6ca3a6"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Mouvement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""d5a967ed-880e-4b8f-b4c4-cdafc089ee4e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouvement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a19bc375-b1b4-4dda-bd50-25ecb37591ed"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Mouvement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""307fad4b-9677-4b78-b76d-0157b5f4bd55"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Mouvement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1f6165cc-4bda-45b1-a431-1244aeb4f53f"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Mouvement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ac228669-2d20-4e11-bb8b-994ec76657a9"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Mouvement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c55a3d39-4bec-4f5c-b7eb-09b497d7b201"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Courrir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1946a964-248d-4de9-bd8c-6036262c1a1c"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Courrir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1c12614-8fb1-486c-8fcf-bd489c060e89"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Accroupir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f293f86-3cfc-46a8-af50-270aa705c889"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Accroupir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6587b868-2667-453c-9c52-8f2c585e3a96"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Accroupir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a44de47-9219-45da-bdb0-30164dd8d640"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Attaque Physique"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8388a101-c8da-409e-a189-a260dcf1cf67"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Attaque Physique"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae02edbc-02eb-478b-b1a6-7c509a2ac906"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5132bb4-3a01-47c8-b795-7b94e25b2997"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c28b2a-139e-462b-99c8-7c7bdbdd5704"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Enclencher Tir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6a5e249-9f84-4ea2-9c9e-6607eec9ef1c"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enclencher Tir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""115c7c50-2b94-4725-91b1-4778ab15b135"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangerClavier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05eb7cf0-a733-4dc8-9e68-5ffb094d0ed7"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangerManette"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""7273262f-e9ab-44b0-9092-3e5fda9096f6"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f593eb4a-7846-453f-9ea0-3764e0a12dee"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""579f9a7c-d47c-40f9-8e06-1c7cb66049a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""b818241c-a0a4-4650-9fb3-e31f58addb45"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""57b8e8d8-3cbb-410d-a666-9337099096a4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""16a36558-4f98-4781-a437-67e1a3eff63a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""913fe955-7ac6-43b7-9610-bf88264f0c26"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""79578643-4c8d-4c1d-aa9e-43613da5824c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""47370111-1046-4487-b428-29f837257416"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDevicePosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""570031e0-8a6c-466c-b374-92d6520d6dd2"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDeviceOrientation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ee643ea9-9650-49ce-bb49-a02fbc1ce796"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""ac37565c-0cd8-439d-890c-2a8824b6c6dc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""62406b1d-601b-4771-8746-bdc0f50f91f7"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""19d6ea8f-3ffa-43ff-828e-427c979de20a"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8dfbcb9c-bb2f-4f77-9a3c-08db20604c72"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5250c064-84b7-4d94-95ac-d2bf5985c9e7"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""98e8b211-77f5-4458-89cc-af2bdca13174"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d78a2009-23ec-436d-a193-8b6c42f915fe"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""777a46f1-18be-4b95-872d-20b9f3e852e8"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ce18b157-69c8-4959-8bc6-a366c6465168"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f3370bc4-4e23-4028-982b-15924b77d58e"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""adb49d4f-f5a3-4f8b-9392-ab8260947bbb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9ea29924-8c3f-4678-96d0-08a265fb939c"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3a4e2007-392d-423f-850b-c8db63512a6b"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5ea9e56b-1f55-4924-a355-696ce66959bc"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""70e837e2-a0ce-4fa3-92bd-59f2c5bdd771"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""c0f3aa84-5424-4bfe-ab43-898a4ed795b5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fc36cf22-d6a1-43b2-9375-180a982dbddd"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c91f364b-4336-49ee-9253-070a926ccb9b"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e6c494b8-7d58-43ed-9b16-20745f0c9319"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1a3158e1-aa38-42e9-bce8-0cea770bb720"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4d11cc3c-3bf6-4214-8f41-f6314b3852c2"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e931d443-177e-424e-8ea6-d7d890b85214"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9c905125-2557-4ec1-9877-960032e2eb11"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""321959f0-3bdc-4f3f-99fe-e20c9db07658"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""49d813d7-7a3f-418e-979f-632f3b2cfde0"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""510a05ce-2b0f-4b27-ab42-6cc4896f32c5"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""887b6e94-c6b4-4a4d-ad92-aa46a16c88b5"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0cdddaa6-1606-4ef5-8464-1b8de611c301"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ada5f712-922e-4515-a440-06f03be5e8ad"",
                    ""path"": ""<Touchscreen>/touch*/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31a45e17-12c9-4016-90f0-37fa1ab6c2ae"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb9f9dd4-a8ec-43db-8643-90a4f89d91ab"",
                    ""path"": ""<Pen>/tip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""569718cb-41f8-4485-a4c4-88e90c2502d5"",
                    ""path"": ""<Touchscreen>/touch*/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a8fe680-e38f-424d-94e8-6e715882c014"",
                    ""path"": ""<XRController>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06575388-08c9-448c-9c07-abd506f106dc"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3bd967f-8c79-4ef6-9231-46e632b8c4fa"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b74d9e5-0f87-4bcc-9c71-c7fb3744ded3"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""738f77d1-e673-488f-b89d-00434d54b698"",
                    ""path"": ""<XRController>/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDevicePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75e0dae4-e894-4c95-a247-7a78ae1e836c"",
                    ""path"": ""<XRController>/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDeviceOrientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // TirLucioles
        m_TirLucioles = asset.FindActionMap("TirLucioles", throwIfNotFound: true);
        m_TirLucioles_PositionSouris = m_TirLucioles.FindAction("Position Souris", throwIfNotFound: true);
        m_TirLucioles_Tir = m_TirLucioles.FindAction("Tir", throwIfNotFound: true);
        m_TirLucioles_AnnulerTir = m_TirLucioles.FindAction("Annuler Tir", throwIfNotFound: true);
        m_TirLucioles_ChangerClavier = m_TirLucioles.FindAction("ChangerClavier", throwIfNotFound: true);
        m_TirLucioles_ChangerManette = m_TirLucioles.FindAction("ChangerManette", throwIfNotFound: true);
        m_TirLucioles_PositionManette = m_TirLucioles.FindAction("Position Manette", throwIfNotFound: true);
        // Mort
        m_Mort = asset.FindActionMap("Mort", throwIfNotFound: true);
        m_Mort_LoadScene = m_Mort.FindAction("LoadScene", throwIfNotFound: true);
        // Dialogues
        m_Dialogues = asset.FindActionMap("Dialogues", throwIfNotFound: true);
        m_Dialogues_LireTexte = m_Dialogues.FindAction("LireTexte", throwIfNotFound: true);
        m_Dialogues_SkipperTexte = m_Dialogues.FindAction("SkipperTexte", throwIfNotFound: true);
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Saut = m_Player.FindAction("Saut", throwIfNotFound: true);
        m_Player_ChangerManette = m_Player.FindAction("ChangerManette", throwIfNotFound: true);
        m_Player_ChangerClavier = m_Player.FindAction("ChangerClavier", throwIfNotFound: true);
        m_Player_Mouvement = m_Player.FindAction("Mouvement", throwIfNotFound: true);
        m_Player_Courrir = m_Player.FindAction("Courrir", throwIfNotFound: true);
        m_Player_Accroupir = m_Player.FindAction("Accroupir", throwIfNotFound: true);
        m_Player_AttaquePhysique = m_Player.FindAction("Attaque Physique", throwIfNotFound: true);
        m_Player_Dash = m_Player.FindAction("Dash", throwIfNotFound: true);
        m_Player_EnclencherTir = m_Player.FindAction("Enclencher Tir", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Navigate = m_UI.FindAction("Navigate", throwIfNotFound: true);
        m_UI_Submit = m_UI.FindAction("Submit", throwIfNotFound: true);
        m_UI_Cancel = m_UI.FindAction("Cancel", throwIfNotFound: true);
        m_UI_Point = m_UI.FindAction("Point", throwIfNotFound: true);
        m_UI_Click = m_UI.FindAction("Click", throwIfNotFound: true);
        m_UI_ScrollWheel = m_UI.FindAction("ScrollWheel", throwIfNotFound: true);
        m_UI_MiddleClick = m_UI.FindAction("MiddleClick", throwIfNotFound: true);
        m_UI_RightClick = m_UI.FindAction("RightClick", throwIfNotFound: true);
        m_UI_TrackedDevicePosition = m_UI.FindAction("TrackedDevicePosition", throwIfNotFound: true);
        m_UI_TrackedDeviceOrientation = m_UI.FindAction("TrackedDeviceOrientation", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TirLucioles
    private readonly InputActionMap m_TirLucioles;
    private ITirLuciolesActions m_TirLuciolesActionsCallbackInterface;
    private readonly InputAction m_TirLucioles_PositionSouris;
    private readonly InputAction m_TirLucioles_Tir;
    private readonly InputAction m_TirLucioles_AnnulerTir;
    private readonly InputAction m_TirLucioles_ChangerClavier;
    private readonly InputAction m_TirLucioles_ChangerManette;
    private readonly InputAction m_TirLucioles_PositionManette;
    public struct TirLuciolesActions
    {
        private @InputJoueur m_Wrapper;
        public TirLuciolesActions(@InputJoueur wrapper) { m_Wrapper = wrapper; }
        public InputAction @PositionSouris => m_Wrapper.m_TirLucioles_PositionSouris;
        public InputAction @Tir => m_Wrapper.m_TirLucioles_Tir;
        public InputAction @AnnulerTir => m_Wrapper.m_TirLucioles_AnnulerTir;
        public InputAction @ChangerClavier => m_Wrapper.m_TirLucioles_ChangerClavier;
        public InputAction @ChangerManette => m_Wrapper.m_TirLucioles_ChangerManette;
        public InputAction @PositionManette => m_Wrapper.m_TirLucioles_PositionManette;
        public InputActionMap Get() { return m_Wrapper.m_TirLucioles; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TirLuciolesActions set) { return set.Get(); }
        public void SetCallbacks(ITirLuciolesActions instance)
        {
            if (m_Wrapper.m_TirLuciolesActionsCallbackInterface != null)
            {
                @PositionSouris.started -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnPositionSouris;
                @PositionSouris.performed -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnPositionSouris;
                @PositionSouris.canceled -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnPositionSouris;
                @Tir.started -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnTir;
                @Tir.performed -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnTir;
                @Tir.canceled -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnTir;
                @AnnulerTir.started -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnAnnulerTir;
                @AnnulerTir.performed -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnAnnulerTir;
                @AnnulerTir.canceled -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnAnnulerTir;
                @ChangerClavier.started -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnChangerClavier;
                @ChangerClavier.performed -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnChangerClavier;
                @ChangerClavier.canceled -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnChangerClavier;
                @ChangerManette.started -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnChangerManette;
                @ChangerManette.performed -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnChangerManette;
                @ChangerManette.canceled -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnChangerManette;
                @PositionManette.started -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnPositionManette;
                @PositionManette.performed -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnPositionManette;
                @PositionManette.canceled -= m_Wrapper.m_TirLuciolesActionsCallbackInterface.OnPositionManette;
            }
            m_Wrapper.m_TirLuciolesActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PositionSouris.started += instance.OnPositionSouris;
                @PositionSouris.performed += instance.OnPositionSouris;
                @PositionSouris.canceled += instance.OnPositionSouris;
                @Tir.started += instance.OnTir;
                @Tir.performed += instance.OnTir;
                @Tir.canceled += instance.OnTir;
                @AnnulerTir.started += instance.OnAnnulerTir;
                @AnnulerTir.performed += instance.OnAnnulerTir;
                @AnnulerTir.canceled += instance.OnAnnulerTir;
                @ChangerClavier.started += instance.OnChangerClavier;
                @ChangerClavier.performed += instance.OnChangerClavier;
                @ChangerClavier.canceled += instance.OnChangerClavier;
                @ChangerManette.started += instance.OnChangerManette;
                @ChangerManette.performed += instance.OnChangerManette;
                @ChangerManette.canceled += instance.OnChangerManette;
                @PositionManette.started += instance.OnPositionManette;
                @PositionManette.performed += instance.OnPositionManette;
                @PositionManette.canceled += instance.OnPositionManette;
            }
        }
    }
    public TirLuciolesActions @TirLucioles => new TirLuciolesActions(this);

    // Mort
    private readonly InputActionMap m_Mort;
    private IMortActions m_MortActionsCallbackInterface;
    private readonly InputAction m_Mort_LoadScene;
    public struct MortActions
    {
        private @InputJoueur m_Wrapper;
        public MortActions(@InputJoueur wrapper) { m_Wrapper = wrapper; }
        public InputAction @LoadScene => m_Wrapper.m_Mort_LoadScene;
        public InputActionMap Get() { return m_Wrapper.m_Mort; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MortActions set) { return set.Get(); }
        public void SetCallbacks(IMortActions instance)
        {
            if (m_Wrapper.m_MortActionsCallbackInterface != null)
            {
                @LoadScene.started -= m_Wrapper.m_MortActionsCallbackInterface.OnLoadScene;
                @LoadScene.performed -= m_Wrapper.m_MortActionsCallbackInterface.OnLoadScene;
                @LoadScene.canceled -= m_Wrapper.m_MortActionsCallbackInterface.OnLoadScene;
            }
            m_Wrapper.m_MortActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LoadScene.started += instance.OnLoadScene;
                @LoadScene.performed += instance.OnLoadScene;
                @LoadScene.canceled += instance.OnLoadScene;
            }
        }
    }
    public MortActions @Mort => new MortActions(this);

    // Dialogues
    private readonly InputActionMap m_Dialogues;
    private IDialoguesActions m_DialoguesActionsCallbackInterface;
    private readonly InputAction m_Dialogues_LireTexte;
    private readonly InputAction m_Dialogues_SkipperTexte;
    public struct DialoguesActions
    {
        private @InputJoueur m_Wrapper;
        public DialoguesActions(@InputJoueur wrapper) { m_Wrapper = wrapper; }
        public InputAction @LireTexte => m_Wrapper.m_Dialogues_LireTexte;
        public InputAction @SkipperTexte => m_Wrapper.m_Dialogues_SkipperTexte;
        public InputActionMap Get() { return m_Wrapper.m_Dialogues; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DialoguesActions set) { return set.Get(); }
        public void SetCallbacks(IDialoguesActions instance)
        {
            if (m_Wrapper.m_DialoguesActionsCallbackInterface != null)
            {
                @LireTexte.started -= m_Wrapper.m_DialoguesActionsCallbackInterface.OnLireTexte;
                @LireTexte.performed -= m_Wrapper.m_DialoguesActionsCallbackInterface.OnLireTexte;
                @LireTexte.canceled -= m_Wrapper.m_DialoguesActionsCallbackInterface.OnLireTexte;
                @SkipperTexte.started -= m_Wrapper.m_DialoguesActionsCallbackInterface.OnSkipperTexte;
                @SkipperTexte.performed -= m_Wrapper.m_DialoguesActionsCallbackInterface.OnSkipperTexte;
                @SkipperTexte.canceled -= m_Wrapper.m_DialoguesActionsCallbackInterface.OnSkipperTexte;
            }
            m_Wrapper.m_DialoguesActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LireTexte.started += instance.OnLireTexte;
                @LireTexte.performed += instance.OnLireTexte;
                @LireTexte.canceled += instance.OnLireTexte;
                @SkipperTexte.started += instance.OnSkipperTexte;
                @SkipperTexte.performed += instance.OnSkipperTexte;
                @SkipperTexte.canceled += instance.OnSkipperTexte;
            }
        }
    }
    public DialoguesActions @Dialogues => new DialoguesActions(this);

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Saut;
    private readonly InputAction m_Player_ChangerManette;
    private readonly InputAction m_Player_ChangerClavier;
    private readonly InputAction m_Player_Mouvement;
    private readonly InputAction m_Player_Courrir;
    private readonly InputAction m_Player_Accroupir;
    private readonly InputAction m_Player_AttaquePhysique;
    private readonly InputAction m_Player_Dash;
    private readonly InputAction m_Player_EnclencherTir;
    public struct PlayerActions
    {
        private @InputJoueur m_Wrapper;
        public PlayerActions(@InputJoueur wrapper) { m_Wrapper = wrapper; }
        public InputAction @Saut => m_Wrapper.m_Player_Saut;
        public InputAction @ChangerManette => m_Wrapper.m_Player_ChangerManette;
        public InputAction @ChangerClavier => m_Wrapper.m_Player_ChangerClavier;
        public InputAction @Mouvement => m_Wrapper.m_Player_Mouvement;
        public InputAction @Courrir => m_Wrapper.m_Player_Courrir;
        public InputAction @Accroupir => m_Wrapper.m_Player_Accroupir;
        public InputAction @AttaquePhysique => m_Wrapper.m_Player_AttaquePhysique;
        public InputAction @Dash => m_Wrapper.m_Player_Dash;
        public InputAction @EnclencherTir => m_Wrapper.m_Player_EnclencherTir;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Saut.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSaut;
                @Saut.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSaut;
                @Saut.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSaut;
                @ChangerManette.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangerManette;
                @ChangerManette.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangerManette;
                @ChangerManette.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangerManette;
                @ChangerClavier.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangerClavier;
                @ChangerClavier.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangerClavier;
                @ChangerClavier.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangerClavier;
                @Mouvement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouvement;
                @Mouvement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouvement;
                @Mouvement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouvement;
                @Courrir.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCourrir;
                @Courrir.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCourrir;
                @Courrir.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCourrir;
                @Accroupir.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAccroupir;
                @Accroupir.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAccroupir;
                @Accroupir.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAccroupir;
                @AttaquePhysique.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttaquePhysique;
                @AttaquePhysique.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttaquePhysique;
                @AttaquePhysique.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttaquePhysique;
                @Dash.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDash;
                @EnclencherTir.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEnclencherTir;
                @EnclencherTir.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEnclencherTir;
                @EnclencherTir.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEnclencherTir;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Saut.started += instance.OnSaut;
                @Saut.performed += instance.OnSaut;
                @Saut.canceled += instance.OnSaut;
                @ChangerManette.started += instance.OnChangerManette;
                @ChangerManette.performed += instance.OnChangerManette;
                @ChangerManette.canceled += instance.OnChangerManette;
                @ChangerClavier.started += instance.OnChangerClavier;
                @ChangerClavier.performed += instance.OnChangerClavier;
                @ChangerClavier.canceled += instance.OnChangerClavier;
                @Mouvement.started += instance.OnMouvement;
                @Mouvement.performed += instance.OnMouvement;
                @Mouvement.canceled += instance.OnMouvement;
                @Courrir.started += instance.OnCourrir;
                @Courrir.performed += instance.OnCourrir;
                @Courrir.canceled += instance.OnCourrir;
                @Accroupir.started += instance.OnAccroupir;
                @Accroupir.performed += instance.OnAccroupir;
                @Accroupir.canceled += instance.OnAccroupir;
                @AttaquePhysique.started += instance.OnAttaquePhysique;
                @AttaquePhysique.performed += instance.OnAttaquePhysique;
                @AttaquePhysique.canceled += instance.OnAttaquePhysique;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @EnclencherTir.started += instance.OnEnclencherTir;
                @EnclencherTir.performed += instance.OnEnclencherTir;
                @EnclencherTir.canceled += instance.OnEnclencherTir;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Navigate;
    private readonly InputAction m_UI_Submit;
    private readonly InputAction m_UI_Cancel;
    private readonly InputAction m_UI_Point;
    private readonly InputAction m_UI_Click;
    private readonly InputAction m_UI_ScrollWheel;
    private readonly InputAction m_UI_MiddleClick;
    private readonly InputAction m_UI_RightClick;
    private readonly InputAction m_UI_TrackedDevicePosition;
    private readonly InputAction m_UI_TrackedDeviceOrientation;
    public struct UIActions
    {
        private @InputJoueur m_Wrapper;
        public UIActions(@InputJoueur wrapper) { m_Wrapper = wrapper; }
        public InputAction @Navigate => m_Wrapper.m_UI_Navigate;
        public InputAction @Submit => m_Wrapper.m_UI_Submit;
        public InputAction @Cancel => m_Wrapper.m_UI_Cancel;
        public InputAction @Point => m_Wrapper.m_UI_Point;
        public InputAction @Click => m_Wrapper.m_UI_Click;
        public InputAction @ScrollWheel => m_Wrapper.m_UI_ScrollWheel;
        public InputAction @MiddleClick => m_Wrapper.m_UI_MiddleClick;
        public InputAction @RightClick => m_Wrapper.m_UI_RightClick;
        public InputAction @TrackedDevicePosition => m_Wrapper.m_UI_TrackedDevicePosition;
        public InputAction @TrackedDeviceOrientation => m_Wrapper.m_UI_TrackedDeviceOrientation;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Navigate.started -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Navigate.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Navigate.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Submit.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @Submit.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @Submit.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @Cancel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                @Point.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Click.started -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @ScrollWheel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @MiddleClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @RightClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                @TrackedDevicePosition.started -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                @TrackedDevicePosition.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                @TrackedDevicePosition.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                @TrackedDeviceOrientation.started -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Navigate.started += instance.OnNavigate;
                @Navigate.performed += instance.OnNavigate;
                @Navigate.canceled += instance.OnNavigate;
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @ScrollWheel.started += instance.OnScrollWheel;
                @ScrollWheel.performed += instance.OnScrollWheel;
                @ScrollWheel.canceled += instance.OnScrollWheel;
                @MiddleClick.started += instance.OnMiddleClick;
                @MiddleClick.performed += instance.OnMiddleClick;
                @MiddleClick.canceled += instance.OnMiddleClick;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
                @TrackedDevicePosition.started += instance.OnTrackedDevicePosition;
                @TrackedDevicePosition.performed += instance.OnTrackedDevicePosition;
                @TrackedDevicePosition.canceled += instance.OnTrackedDevicePosition;
                @TrackedDeviceOrientation.started += instance.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.performed += instance.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.canceled += instance.OnTrackedDeviceOrientation;
            }
        }
    }
    public UIActions @UI => new UIActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface ITirLuciolesActions
    {
        void OnPositionSouris(InputAction.CallbackContext context);
        void OnTir(InputAction.CallbackContext context);
        void OnAnnulerTir(InputAction.CallbackContext context);
        void OnChangerClavier(InputAction.CallbackContext context);
        void OnChangerManette(InputAction.CallbackContext context);
        void OnPositionManette(InputAction.CallbackContext context);
    }
    public interface IMortActions
    {
        void OnLoadScene(InputAction.CallbackContext context);
    }
    public interface IDialoguesActions
    {
        void OnLireTexte(InputAction.CallbackContext context);
        void OnSkipperTexte(InputAction.CallbackContext context);
    }
    public interface IPlayerActions
    {
        void OnSaut(InputAction.CallbackContext context);
        void OnChangerManette(InputAction.CallbackContext context);
        void OnChangerClavier(InputAction.CallbackContext context);
        void OnMouvement(InputAction.CallbackContext context);
        void OnCourrir(InputAction.CallbackContext context);
        void OnAccroupir(InputAction.CallbackContext context);
        void OnAttaquePhysique(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnEnclencherTir(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnNavigate(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
        void OnMiddleClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnTrackedDevicePosition(InputAction.CallbackContext context);
        void OnTrackedDeviceOrientation(InputAction.CallbackContext context);
    }
}
